title: Castelo
views:
  - title: Home
    cards:
      - type: sensor
        entity: sensor.water_level
        name: Caixa d'Água
        #line_color: "#3498db"
        accuracy: 50
        height: 150
        detail: 2
        graph: line
        unit: "%"

      - type: entities
        title: Sensors
        show_header_toggle: false
        entities:
          #- sensor.water_level
          - sensor.vl53l1x
          - sensor.water_level_mm
          - sensor.htu21d_sensor_humidity
          - sensor.htu21d_sensor_temperature
          - sensor.bh1750_light_sensor
          #- sun.sun

      - type: gauge
        title: CPU
        name: CPU
        show_header_toggle: true
        entity: sensor.processor_use
        severity:
          green: 0
          yellow: 70
          red: 90

      - type: entities
        title: Raspberry Pi
        show_header_toggle: false
        entities:
          - sensor.memory_free
          - sensor.network_in_wlan0
          - sensor.network_out_wlan0
          - sensor.disk_use_percent_home

